[package]
name = "runix"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/entry.rs"
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2"
spin = "0.9"
x86_64 = "0.14"
bit_field = "0.10.2"
num_enum = { version = "0.7.0", default-features = false }