[package]
name = "runix"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.6"
spin = "0.9"
#multiboot2 = {version ="0.18.1",  default-features = false}
