[package]
name = "runix"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/entry.rs"
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.6"
spin = "0.9"
#multiboot2 = {version ="0.18.1",  default-features = false}
static_cell = { version = "1.2.0", features = ["nightly"] }
